[general]
import = [
    "~/.config/alacritty/themes/alacritty_0_12.toml"
]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "Iosevka Nerd Font" }
size = 14
offset = { x = 0, y = 3 }

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 1
class = { general = "Alacritty", instance = "Alacritty" }
padding = { x = 0, y = 0 }

[cursor]
# style = { shape = "Beam", blinking = "Never" }
thickness = 0.2
